//package com.springapp.mvc;
//
//import mvc.common.CategoryInfo;
//import mvc.common.GoodInfo;
//import mvc.repositories.CategoryRepository;
//import mvc.repositories.GoodRepository;
//import org.springframework.context.support.ClassPathXmlApplicationContext;
//
//import java.io.IOException;
//import java.math.BigDecimal;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.SQLException;
//import java.sql.Statement;
//
//public class CreateTable {
//
//    public static void main(String[] args) {
//        try {
//            createTableGoods();
//            createTableCategory();
//            testInsert();
////            testUpdate();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
//
//    private static Connection getConnection() throws IOException, ClassNotFoundException, SQLException {
////        Properties props = new Properties();                  // Доп класс для считывание данных с файла
////        props.load(new FileInputStream("etc/properties/tutor-db-connection.properties"));     // Считывание (загрузка) из файла
////        String driver = props.getProperty("driver");
//        String url = "jdbc:h2:c:/Java/h2db/SpringProject";
//        String user = "sa";
//        String pass = "";
//        Class.forName("org.h2.Driver");                       // Проверка правильности подключения драйвера
//        return DriverManager.getConnection(url, user, pass);  // Открытие соединения к БД
//    }
//
//    private static void createTableGoods() throws SQLException, ClassNotFoundException, IOException {
//        Connection connection = null;
//        try {
//            connection = getConnection();
//            Statement statement = connection.createStatement();
//            statement.executeUpdate("create table if not exists GOODS " +
//                    "(id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, " +
//                    "name VARCHAR(50), description varchar(200), imageUrl VARCHAR(150), " +
//                    "price DOUBLE(5), categoryId bigint(10))");
//        } finally {
//            if (connection != null) {
//                connection.close();
//            }
//        }
//    }
//
//    private static void createTableCategory() throws SQLException, ClassNotFoundException, IOException {
//        Connection connection = null;
//        try {
//            connection = getConnection();
//            Statement statement = connection.createStatement();
//            statement.executeUpdate("create table if not exists CATEGORY " +
//                    "(id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, " +
//                    "name varchar(50), parentId bigint)");
//        } finally {
//            if (connection != null) {
//                connection.close();
//            }
//        }
//    }
//
//    private static void testInsert() {
//        init();
//
//        CategoryInfo category = new CategoryInfo(1L, "Тестовая категория", null);
//        categoryRepository.addCategory(category);
//        goodRepository.addGood(new GoodInfo("Book1",new BigDecimal(87),category,"BestSeller",19L,"Pushkin","Russia",300L,
//                "/images/pushkin/book1.jpg","lalaalllallalal"));
//        goodRepository.addGood(new GoodInfo("Book2",new BigDecimal(36),category,"New arrival",20L,"Dostoevskiy","Russia",98L,
//                "/images/dostoevskiy/book2.jpg","lalalallalal2"));
//        goodRepository.addGood(new GoodInfo("Book3",new BigDecimal(72),category, "New arrival", 21L, "Akhmatova","Russia",520L,
//                "/images/akhmatova/book3.jpg","lalalalallala3"));
//    }
//
//    private static void testUpdate() {
//        init();
//        CategoryInfo category = new CategoryInfo(1L, "Тестовая категория", null);
//        goodRepository.updateGood(new GoodInfo("Book3", new BigDecimal(120),category, "New arrival", 21L, "Akhmatova", "Russia",230L,
//                "images/akhmatova/book3.jpg","lalallalallalal*UPDATED*"));
//    }
//
//    private static GoodRepository goodRepository;
//    private static CategoryRepository categoryRepository;
//
//    private static void init() {
//        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(
//                new String[] { "spring-jdbc.xml" }, true);
//        goodRepository = context.getBean(GoodRepository.class);
//        categoryRepository = context.getBean(CategoryRepository.class);
//    }
//}
